import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  TextInput,
  Alert,
  SafeAreaView,
  KeyboardAvoidingView,
  Platform,
  Linking,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { StackNavigationProp } from '@react-navigation/stack';
import { RootStackParamList } from '../../App';
import { useCallDetection } from '../contexts/CallDetectionContext';
import CustomIcon from '../components/CustomIcon';

type HomeScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Home'>;

const HomeScreen: React.FC = () => {
  const navigation = useNavigation<HomeScreenNavigationProp>();
  const { callHistory } = useCallDetection();
  const [phoneNumber, setPhoneNumber] = useState<string>('');

  // Checklist state
  const [checklist, setChecklist] = useState([
    { id: 'speakerphone', text: 'Call is on speakerphone', checked: false, icon: 'phone-in-talk' },
    { id: 'volume', text: 'Volume is turned up', checked: false, icon: 'volume-high' },
    { id: 'number', text: 'Phone number is verified', checked: false, icon: 'phone-check' },
  ]);

  // Check if all items are checked
  const allChecked = checklist.every(item => item.checked);

  // Toggle checklist item
  const toggleChecklistItem = (id: string) => {
    setChecklist(prev =>
      prev.map(item =>
        item.id === id ? { ...item, checked: !item.checked } : item
      )
    );
  };

  // Handle scan call
  const handleScanCall = () => {
    if (!allChecked) {
      Alert.alert('Checklist Incomplete', 'Please complete all checklist items before scanning to ensure proper voice recording.');
      return;
    }

    navigation.navigate('CallScan', { phoneNumber: phoneNumber.trim() });
  };

  // Render recent call history item
  const renderCallHistoryItem = (call: any, index: number) => {
    if (!call) return null;

    const isAI = call.isAI || call.isAIDetected;
    const date = new Date(call.timestamp);
    const formattedDate = `${date.toLocaleDateString()} ${date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;

    return (
      <TouchableOpacity
        key={index}
        style={styles.historyItem}
        onPress={() => navigation.navigate('CallHistory')}
      >
        <View style={styles.historyItemLeft}>
          <CustomIcon
            name={isAI ? "robot" : "account"}
            size={24}
            color={isAI ? "#EF4444" : "#10B981"}
          />
          <View style={styles.historyItemTextContainer}>
            <Text style={styles.historyItemPhone}>{call.phoneNumber || "Unknown"}</Text>
            <Text style={styles.historyItemDate}>{formattedDate}</Text>
          </View>
        </View>
        <View style={[styles.resultBadge, { backgroundColor: isAI ? "#FEE2E2" : "#D1FAE5" }]}>
          <Text style={[styles.resultBadgeText, { color: isAI ? "#B91C1C" : "#047857" }]}>
            {isAI ? "AI" : "Human"}
          </Text>
        </View>
      </TouchableOpacity>
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.keyboardAvoidingView}
      >
        <ScrollView style={styles.scrollView} contentContainerStyle={styles.scrollViewContent}>
          <View style={styles.header}>
            <Text style={styles.title}>VoiceGuard AI</Text>
            <TouchableOpacity
              style={styles.settingsButton}
              onPress={() => navigation.navigate('Settings')}
            >
              <CustomIcon name="cog" size={24} color="#4F46E5" />
            </TouchableOpacity>
          </View>

          <View style={styles.mainCard}>
            <View style={styles.cardHeader}>
              <CustomIcon name="voicemail" size={32} color="#4F46E5" />
              <Text style={styles.cardTitle}>Voicemail Scanner</Text>
            </View>

            <Text style={styles.cardDescription}>
              Analyze your voicemails to detect if they're from a real person or generated by AI. Protect yourself from scams.
            </Text>
            
            <View style={styles.voicemailInstructionsContainer}>
              <Text style={styles.voicemailInstructionsTitle}>How to scan a voicemail:</Text>
              <View style={styles.voicemailStep}>
                <Text style={styles.voicemailStepNumber}>1</Text>
                <Text style={styles.voicemailStepText}>In the Phone app, open your voicemail</Text>
              </View>
              <View style={styles.voicemailStep}>
                <Text style={styles.voicemailStepNumber}>2</Text>
                <Text style={styles.voicemailStepText}>Tap the share icon and select "Save to Files"</Text>
              </View>
              <View style={styles.voicemailStep}>
                <Text style={styles.voicemailStepNumber}>3</Text>
                <Text style={styles.voicemailStepText}>Use the button below to upload and analyze</Text>
              </View>
            </View>
            
            <TouchableOpacity
              style={styles.voicemailButton}
              onPress={() => navigation.navigate('VoicemailScan')}
            >
              <CustomIcon name="upload" size={20} color="#FFFFFF" style={styles.voicemailButtonIcon} />
              <Text style={styles.voicemailButtonText}>Scan Voicemail</Text>
            </TouchableOpacity>

            <View style={styles.comingSoonContainer}>
              <View style={styles.comingSoonHeader}>
                <CustomIcon name="phone-check" size={24} color="#4F46E5" />
                <Text style={styles.comingSoonTitle}>Help Us Fight Scams</Text>
                <View style={[styles.comingSoonBadge, { backgroundColor: '#EBF5FF' }]}>
                  <Text style={[styles.comingSoonBadgeText, { color: '#1E40AF' }]}>Take Action</Text>
                </View>
              </View>
              <Text style={styles.comingSoonDescription}>
                We need your help! iOS and Android don't allow live call recording, which prevents us from stopping scams in real-time. Sign our petition to push for change.
              </Text>
              <TouchableOpacity 
                style={styles.petitionButton}
                onPress={() => Linking.openURL('https://www.voiceguard.ai/petition')}
              >
                <Text style={styles.petitionButtonText}>Sign the Petition</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.historySection}>
            <View style={styles.historySectionHeader}>
              <Text style={styles.historySectionTitle}>Recent Scans</Text>
              {callHistory.length > 0 && (
                <TouchableOpacity onPress={() => navigation.navigate('CallHistory')}>
                  <Text style={styles.viewAllText}>View All</Text>
                </TouchableOpacity>
              )}
            </View>

            {callHistory.length > 0 ? (
              <View style={styles.historyList}>
                {callHistory.slice(0, 3).map((call, index) => renderCallHistoryItem(call, index))}
              </View>
            ) : (
              <View style={styles.emptyHistory}>
                <CustomIcon name="history" size={48} color="#D1D5DB" />
                <Text style={styles.emptyHistoryText}>No scan history yet</Text>
                <Text style={styles.emptyHistorySubtext}>Your scan results will appear here</Text>
              </View>
            )}
          </View>

          {/* Help & Tutorial Button */}
          <TouchableOpacity 
            style={styles.helpButton}
            onPress={() => {
              // Navigate to onboarding screens for tutorial
              navigation.navigate('Onboarding');
            }}
          >
            <CustomIcon name="help-circle" size={20} color="#4F46E5" />
            <Text style={styles.helpButtonText}>Help & Tutorial</Text>
          </TouchableOpacity>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  settingsButton: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#EEF2FF',
  },
  mainCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginLeft: 12,
  },
  cardDescription: {
    fontSize: 16,
    color: '#4B5563',
    marginBottom: 20,
    lineHeight: 22,
  },
  voicemailInstructionsContainer: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  voicemailInstructionsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  voicemailStep: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  voicemailStepNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#4F46E5',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '600',
    marginRight: 12,
  },
  voicemailStepText: {
    fontSize: 15,
    color: '#4B5563',
    flex: 1,
  },
  voicemailButton: {
    backgroundColor: '#4F46E5',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  voicemailButtonIcon: {
    marginRight: 8,
  },
  voicemailButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  comingSoonContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 8,
  },
  comingSoonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  comingSoonTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#9CA3AF',
    marginLeft: 8,
    flex: 1,
  },
  comingSoonBadge: {
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  comingSoonBadgeText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6B7280',
  },
  comingSoonDescription: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 16,
  },
  petitionButton: {
    backgroundColor: '#1E40AF',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  petitionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  phoneInputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  phoneInput: {
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#111827',
  },
  checklistContainer: {
    marginBottom: 20,
  },
  checklistTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#4F46E5',
    borderColor: '#4F46E5',
  },
  checklistIcon: {
    marginRight: 8,
  },
  checklistText: {
    fontSize: 15,
    color: '#4B5563',
  },
  scanButton: {
    backgroundColor: '#4F46E5',
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanButtonDisabled: {
    backgroundColor: '#A5B4FC',
  },
  scanButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  scanButtonIcon: {
    marginLeft: 4,
  },
  historySection: {
    marginBottom: 24,
  },
  historySectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  historySectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  viewAllText: {
    fontSize: 14,
    color: '#4F46E5',
    fontWeight: '500',
  },
  historyList: {
    marginTop: 8,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  historyItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  historyItemTextContainer: {
    marginLeft: 12,
  },
  historyItemPhone: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    marginBottom: 4,
  },
  historyItemDate: {
    fontSize: 14,
    color: '#6B7280',
  },
  resultBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  resultBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  emptyHistory: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  emptyHistoryText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6B7280',
    marginTop: 12,
    marginBottom: 4,
  },
  emptyHistorySubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  helpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 16,
  },
  helpButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#4F46E5',
    marginLeft: 8,
  }
});

export default HomeScreen;
